art/urls.py
from django.urls import path
from .views import ArtDetailView, CreateArtView, save_art
app_name = 'art'
urlpatterns = [
    path("art_deltail/<int:art_id>/", ArtDetailView.as_view(), name = "art_deltail"),
    path("create_art/", CreateArtView.as_view(), name = "create_art"),
    path("save_art/<int:user_id>/", save_art, name = "save_art"),
]

home/urls.py
from django.urls import path
from .views import home
app_name = 'home'
urlpatterns = [
    path("", home, name = "home"),
]

string_art/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include('home.urls')),
    path("art/", include('art.urls')),
    path("user/", include('user.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

user/urls.py
from django.urls import path
from .views import CreateUserView, LoginView, LogoutView, EditUserView, contact_submit
app_name = 'user'

urlpatterns = [
    path("create_user/", CreateUserView.as_view(), name = "create_user"),
    path("login/", LoginView.as_view(), name = "login"),
    path("logout/", LogoutView.as_view(), name = "logout"),
    path("edit/<int:user_id>/", EditUserView.as_view(), name = "edit_user"),
    path("contact/<int:user_id>/", contact_submit, name = "contact"),
    path("contact/", contact_submit, name = "contact_no_id"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from art.models import Art


# Create your views here.
def home(request):
    if 'image_path' in request.session:
        del request.session['image_path']
    art_rectangular = Art.objects.filter(categories__name='Rectangular', is_published=True)
    art_circle = Art.objects.filter(categories__name='Circular (black & white)', is_published=True)
    art_digital_prints = Art.objects.filter(categories__name='Digital Prints', is_published=True)
    context = {
        'art_rectangular': art_rectangular, 
        'art_circle' : art_circle,
        'art_digital_prints' : art_digital_prints
    }
    return render(request, 'home/home.html', context=context)

home/templates/home/home.html
{% extends 'home/layout.html' %}
{% load static %}

{% block title %}
  Trang chủ
{% endblock %}

{% block content %}
  <div class="content d-flex justify-content-center align-items-center vh-100" id="background_head" style="background-image: url('{% static 'img/tettt.png' %}'); 
      background-size: cover;
      background-repeat: no-repeat;">
    <img src="{% static 'img/logo.png' %}" alt="" class="m-10" id="logo-head" />
  </div>
  <div class="container pt-5" id='intro' style="height: 100vh; width: 100%; background-color: dimgray;">
    <div class="row">
      <h1 class="text-center">String Art</h1>
      <h4 class="text-center">Chào mừng bạn đến với nghệ thuật từ dây</h4>
      <hr>
      <div class="col-sm-6">
        <div class="row">
          <div class="container m-4">
            <div class="row">
              <div class="col-sm-4">
                <img src="{% static 'img/MaryEverestBoole.jpeg' %}" alt="" class="mr-auto">
              </div>
              <div class="col-sm-8">
                  <p>
                    Nghệ thuật từ dây lần đầu được đưa ra bởi một người giáo viên nữ người Anh có tên là MaryEverestBoole
                    <br>
                    Việc cho học sinh tạo nên các tác phẩm từ dây đã góp phần giúp chúng tăng khả năng hình học, tư duy logic và sáng tạo
                  </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="row">
          <div class="container m-4">
            <div class="row">
              <div class="col-sm-4">
                <img src="{% static 'img/001.jpg' %}" alt="" style="width: 100%; height: auto;">
              </div>
              <div class="col-sm-8">
                <p>
                  Một String Art bao gồm các thành phần sau đây
                </p>
                <ul>
                  <li>
                    <p>
                      <b>Khung tranh</b>
                    </p>
                  </li>
                  <li>
                    <p>
                      <b>Đinh neo</b>
                    </p>
                  </li>
                  <li>
                    <p>
                      <b>Dây</b>
                    </p>
                  </li>
                </ul>
                <p>Việc kết hợp ba thành phần trên, ta có tạo ra được các tác phẩm nghệ thuật từ dây</p>
                
              </div>
            </div>
            <div class="row mt-5">
              <div class="content">
                <h4>
                  Bạn có thể tự tạo cho mình một tác phẩm <a class="text-white link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="{% url 'art:create_art' %}">tại đây</a>
                </h4>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row art-row justify-content-center mt-5">
      {% for art in art_rectangular %}
        <div class="col-sm-4 card-container mt-5 position-relative">
          <div class="col-sm-12">
            <div class="card text-white" style="background-color: black;">
              <div class="card-header">
                <img src="{{ art.image1.url }}" alt="hình ảnh" class="img-fluid fixed-size-img" style="width: 100%; height: auto;" />
              </div>
              <div class="card-body mb-5">
                <h5 class="card-title">{{ art.title }}</h5>
              </div>
            </div>
          </div>
          <div class="col-sm-12 mt-auto d-flex justify-content-center position-absolute" style="bottom: 0; right: 0; top: auto;">
            <button class="btn btn-secondary" onclick="window.location.href='{% url 'art:art_deltail' art.id %}'">Xem thêm</button>
          </div>
        </div>
      {% endfor %}
    </div>
    <div id="contact" class="container mt-5 bg-dark p-4">
      <h2 class="text-center">Liên hệ</h2>
      <div class="row justify-content-center">
        <div class="col-md-6">
          {% if user.is_authenticated %}
          <form action="{% url 'user:contact' user.id %}" method="post">
          {% else %}
          <form action="{% url 'user:contact_no_id'%}" method="post">
          {% endif %}
            {% csrf_token %}
            <div class="row">
              <div class="col-sm-6">
                <label for="firstname" class="form-label">Tên:</label>
                <input type="text" class="form-control" id="firstname" name="firstname" required 
                {% if user.is_authenticated %}
                value="{{ user.firstname }}"
                {% endif %}>
              </div>
              <div class="col-sm-6">
                <label for="lastname" class="form-label">Họ:</label>
                <input type="text" class="form-control" id="lastname" name="lastname" required
                {% if user.is_authenticated %}
                value="{{ user.lastname }}"
                {% endif %}>
                
              </div>
            </div>
            <div class="mb-3">
              <label for="email" class="form-label">Email:</label>
              <input type="email" class="form-control" id="email" name="email" required
              {% if user.is_authenticated %}
              value="{{ user.email }}"
              {% endif %}>
            </div>
            <div class="mb-3">
              <label for="message" class="form-label">Tin nhắn:</label>
              <textarea class="form-control" id="message" name="message" rows="5" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Gửi</button>
          </form>
        </div>
      </div>
    </div>
    

    <div class="row art-row justify-content-center bg-white mt-5 mb-5">
      {% for art in art_circle %}
        {% if art.is_published %}
        <div class="col-sm-4 card-container mt-5 position-relative mb-5">
          <div class="col-sm-12">
            <div class="card text-black bg-transparent border-0 p-0">
              <div class="card-header p-0 border-0">
                <img src="{{ art.image1.url }}" alt="hình ảnh" class="img-fluid fixed-size-img" style="width: 100%; height: auto;" />
              </div>
              <div class="card-body mb-5">
                <h5 class="card-title">{{ art.title }}</h5>
              </div>
            </div>
          </div>
          <div class="col-sm-12 mt-auto d-flex justify-content-center position-absolute" style="bottom: 0; right: 0; top: auto;">
            <button class="btn btn-secondary" onclick="window.location.href='{% url 'art:art_deltail' art.id %}'">Xem thêm</button>
          </div>
        </div>  
        {% endif %}
      {% endfor %}
    </div>

    <div class="row art-row justify-content-center mt-5">
      {% for art in art_digital_prints %}
        <div class="col-sm-4 card-container mt-5 position-relative mb-5">
          <div class="col-sm-12">
            <div class="card text-white" style="background-color: black;">
              <div class="card-header">
                <img src="{{ art.image1.url }}" alt="hình ảnh" class="img-fluid fixed-size-img" style="width: 100%; height: auto;" />
              </div>
              <div class="card-body mb-5">
                <h5 class="card-title">{{ art.title }}</h5>
              </div>
            </div>
          </div>
          <div class="col-sm-12 mt-auto d-flex justify-content-center position-absolute" style="bottom: 0; right: 0; top: auto;">
            <button class="btn btn-secondary" onclick="window.location.href='{% url 'art:art_deltail' art.id %}'">Xem thêm</button>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

home/templates/home/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row content p-2" style="background-color: #555;" id="navbar">
        <div class="col-sm-2 d-flex justify-content-center align-items-center">
          <a class="navbar-brand" href="{% url 'home:home' %}">
            <img src="{% static 'img/logo.png' %}" alt="Avatar Logo" style="width:100px;" class="rounded-pill" />
          </a>
        </div>
        <div class="col-sm-8 d-flex justify-content-center align-items-center">
          <div class="row">
            <ul class="nav">
              <li class="nav-item">
                <a class="nav-link text-white btn btn-dark" href="{% url 'home:home' %}#intro">Giới thiệu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white btn btn-dark" href="{% url 'art:create_art' %}">Tạo tranh chỉ</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white btn btn-dark" href="{% url 'home:home' %}#contact">Liên hệ</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2 d-flex justify-content-center align-items-center">
          <div class="row">
            {% if user.is_authenticated %}

            <div class="col-sm-4">
              <a class="nav-link text-white text-right ms-auto" href="{% url 'user:edit_user' user.id %}">
                <img src="{% if user.image %}
                    {{ user.image.url }}
                  {% else %}
                    {% static 'img/default.png' %}
                  {% endif %}"
                  alt="Avatar Logo"
                  style="width:50px; height: 50px; object-fit: cover;"
                  class="rounded-pill ms-auto" />
              </a>
            </div>
            <div class="col-sm-8">
              <p class="row  mr-auto text-right">
                Xin chào, {{ user.username }}!
              </p>
              <a class="nav-link text-white text-right btn btn-dark" href="{% url 'user:logout' %}">Đăng xuất</a>
              {% else %}
                <a class="nav-link text-white text-right ms-auto btn btn-dark" href="{% url 'user:login' %}">Đăng nhập</a>
                <a class="nav-link text-white text-right ms-auto btn btn-dark" href="{% url 'user:create_user' %}">Đăng ký</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <div id="alert-success">
        {% if messages %}
          {% for message in messages %}
          {% if message.tags == 'error' %}
              <div class="alert alert-danger top-{{ forloop.counter0 }} end-0 m-3" role="alert" id="alert-danger" style="padding: auto;">
          {% elif message.tags == 'success' %}
              <div class="alert alert-success top-{{ forloop.counter0 }} end-0 m-3" role="alert" id="alert-success" style="padding: auto;">
          {% endif %}
              <strong>{{ message }}</strong>
          </div>
          {% endfor %}
    
    
        {% endif %}
        {% if success %}
            <div class="alert alert-success top-2 end-0 m-3" role="alert" id="alert-success" style="padding: auto;">
                <strong>{{ success }}</strong>
            </div>
        {% endif %}
      </div>
      <div class="row">
        {% block content %}

        {% endblock %}
      </div>
    </div>
    <footer class="footer mt-auto py-3">
      <div class="container">
        <span class="text-white">Copyright &copy; 2020</span>
      </div>
    </footer>
  </body>
</html>

<script>
  $(document).ready(function(){
    var windowHeight = $(window).height();
    var bodyHeight = $('body').height();

    if(bodyHeight < windowHeight){
        $('footer').css('position', 'fixed');
        $('footer').css('bottom', '0');
        $('footer').css('width', '100%');
    }
});

</script>