art/urls.py
from django.urls import path
from .views import ArtDetailView, CreateArtView, save_art
app_name = 'art'
urlpatterns = [
    path("art_deltail/<int:art_id>/", ArtDetailView.as_view(), name = "art_deltail"),
    path("create_art/", CreateArtView.as_view(), name = "create_art"),
    path("save_art/<int:user_id>/", save_art, name = "save_art"),
]

string_art/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include('home.urls')),
    path("art/", include('art.urls')),
    path("user/", include('user.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

art/models.py
from django.db import models
from user.models import User 
# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True)
    def __str__(self):
        return self.name
    
class Art(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    image1 = models.FileField(max_length=255, null= True)
    image2 = models.FileField(max_length=255, null=True, blank=True)
    categories = models.ForeignKey(Categories, on_delete=models.CASCADE, default='')
    artists = models.ForeignKey( User, on_delete=models.CASCADE)
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.title}   -   {self.categories}"

art/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.ImageField()

art/views.py
from django.shortcuts import render, redirect
from django.views import View
from art.models import Art
from django.contrib import messages
import os
from .algorithm.generate import create_string_art
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from django.conf import settings
from datetime import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Art, Categories
from user.models import User
from django.core.files import File
import uuid

# Create your views here.
class ArtDetailView(View):
    def get(self, request, art_id):
        art = Art.objects.get(id=art_id)
        return render(request, 'art/art_deltail.html', {'art': art})
    def post(self, request, art_id):
        art = Art.objects.get(id=art_id)
        return render(request, 'art/art_deltail.html', {'art': art})


class CreateArtView(View):
    def get(self, request):
        # Lấy đường dẫn ảnh kết quả từ session
        image_result = request.session.get('image_path', None)
        image_root = request.session.get('image_root', None)
        wb = request.session.get('wb_{}'.format(image_result), None)
        rgb = request.session.get('rgb_{}'.format(image_result), None)
        rect = request.session.get('rect_{}'.format(image_result), None)
        if request.session.get('image_processed_{}'.format(image_result), False):
            return render(request, 'art/create_art.html', {'image_processed'.format(image_result): True,
                                                            'image_result': image_result,
                                                            'image_root': image_root,
                                                            'wb': wb,
                                                            'rgb': rgb,
                                                            'rect': rect})
        else:
            return render(request, 'art/create_art.html', {'image_processed_{}'.format(image_result): False,
                                                            'image_result': image_result,
                                                            'image_root': image_root,
                                                            'wb': wb,
                                                            'rgb': rgb,
                                                            'rect': rect})
    
    
    def post(self, request):
        if 'image' in request.FILES:
            image = request.FILES['image'] # lấy ảnh từ request
            file_path = os.path.join(settings.MEDIA_ROOT, image.name)
            with open(file_path, 'wb') as destination:
                for chunk in image.chunks():
                    destination.write(chunk)
            
            # lấy các giá trị của form
            pull_amount = 2000
            side_len = 300
            export_strength = 0.1
            random_nails = None
            radius1_multiplier = 1
            radius2_multiplier = 1
            nail_step = 4
            wb = False
            rgb = False
            rect = False

            if request.POST.get('pull_amount'):
                pull_amount = int(request.POST.get('pull_amount'))
            if request.POST.get('side_len'):
                side_len = int(request.POST.get('side_len'))
            if request.POST.get('export_strength'):
                export_strength = float(request.POST.get('export_strength'))
            if request.POST.get('random_nails'):
                random_nails = int(request.POST.get('random_nails'))
            if request.POST.get('radius1_multiplier'):
                radius1_multiplier = float(request.POST.get('radius1_multiplier'))
            if request.POST.get('radius2_multiplier'):
                radius2_multiplier = float(request.POST.get('radius2_multiplier'))
            if 'nail_step' in request.POST:
                nail_step = int(request.POST.get('nail_step'))
            if 'wb' in request.POST:
                wb = request.POST['wb'] == 'True'
            if 'rgb' in request.POST:
                rgb = request.POST['rgb'] == 'True'
            if 'rect' in request.POST:
                rect = request.POST['rect'] == 'True'

            # gọi hàm create_string_art
            result = create_string_art(
                                        input_file = file_path,
                                        side_len=side_len,
                                        export_strength=export_strength,
                                        pull_amount=pull_amount,
                                        random_nails=random_nails,
                                        radius1_multiplier=radius1_multiplier,
                                        radius2_multiplier=radius2_multiplier,
                                        nail_step=nail_step,
                                        wb=wb, 
                                        rgb=rgb, 
                                        rect=rect
                                        )
            

            result_path = file_path + '_result.png'  # Đường dẫn của file kết quả
            mpimg.imsave(result_path, result, cmap=plt.get_cmap("gray"), vmin=0.0, vmax=1.0) # tạo và lưu ảnh vào đường dẫn result_path
            image_result = "/Uploads/" + '/'.join(result_path.split('/')[-1:]) # tạo đường dẫn ảnh để gửi về templates
            image_root = "/Uploads/" + '/'.join(file_path.split('/')[-1:]) # tạo đường dẫn đến hình gốc
            # Đặt biến session để xác định việc xử lý đã được thực hiện
            request.session['image_processed_{}'.format(image_result)] = True
            request.session['image_path'] = image_result  # Lưu đường dẫn của file kết quả vào session
            request.session['image_root'] = image_root  # Lưu đường dẫn của file gốc vào session
            request.session['wb_{}'.format(image_result)] = wb
            request.session['rgb_{}'.format(image_result)] = rgb
            request.session['rect_{}'.format(image_result)] = rect
            messages.success(request, 'Hoàn tất tạo tranh chỉ')

            return HttpResponseRedirect(reverse('art:create_art'))

        else:
            messages.error(request, "Lấy file không thành công")
            image_result = None
            return render(request, 'art/create_art.html', {'image_result': image_result})


def save_art(request, user_id):
    user = User.objects.get(id=user_id)
    if request.method == 'POST':
        title = request.POST['title']
        description = request.POST['description']
        image_result = os.getcwd() + request.session.get('image_path', None)
        image_root = os.getcwd() + request.session.get('image_root', None)

        wb = request.session.get('wb_{}'.format('image_result'), None)
        rgb = request.session.get('rgb_{}'.format('image_result'), None)
        rect = request.session.get('rect_{}'.format('image_result'), None)
        is_published = request.POST.get('is_published', False)
        if rect == 'True':
            category = Categories.objects.get(name="Rectangular")
        elif rgb == 'True':
            category = Categories.objects.get(name="Circular (colour)")
        else:
            category = Categories.objects.get(name="Circular (black & white)")
        art = Art.objects.create(artists=user, title=title, description=description, categories=category, is_published=is_published)

        unique_identifier = str(uuid.uuid4())[:8] #tạo chuỗi duy nhất gắn với ảnh

        # Thêm phần tử duy nhất vào tên file
        image1_filename = '{}_{}'.format(unique_identifier, image_result.split('/')[-1])
        image2_filename = '{}_{}'.format(unique_identifier, image_root.split('/')[-1])

        # Tạo đối tượng File từ đường dẫn của hình ảnh và gán cho trường image1
        if image_result:
            image1_file = File(open(image_result, 'rb'))
            art.image1.save(image1_filename, image1_file, save=True)

        # Tạo đối tượng File từ đường dẫn của hình ảnh và gán cho trường image2
        if image_root:
            image2_file = File(open(image_root, 'rb'))
            art.image2.save(image2_filename, image2_file, save=True)

        art.save()
        messages.success(request, 'Bạn đã tạo thành công tranh ch')
    
    return HttpResponseRedirect(reverse('art:create_art'))

art/templates/art/art_deltail.html
{% extends 'home/layout.html' %}

{% block content %}
<style>
  * {box-sizing: border-box;}
  
  .img-comp-container {
    position: relative;
    height: 200px; /*should be the same height as the images*/
  }
  
  .img-comp-img {
    position: absolute;
    width: auto;
    height: auto;
    overflow:hidden;
  }
  
  .img-comp-img img {
    display:block;
    vertical-align:middle;
  }
  
  .img-comp-slider {
    position: absolute;
    z-index:9;
    cursor: ew-resize;
    /*set the appearance of the slider:*/
    width: 40px;
    height: 40px;
    background-color: #2196F3;
    opacity: 0.7;
    border-radius: 50%;
  }
  </style>
<script>
  function initComparisons() {
    var x, i
    /*find all elements with an "overlay" class:*/
    x = document.getElementsByClassName('img-comp-overlay')
    for (i = 0; i < x.length; i++) {
      /*once for each "overlay" element:
        pass the "overlay" element as a parameter when executing the compareImages function:*/
      compareImages(x[i])
    }
    function compareImages(img) {
      var slider,
        img,
        clicked = 0,
        w,
        h
      /*get the width and height of the img element*/
      w = img.offsetWidth
      h = img.offsetHeight
      /*set the width of the img element to 50%:*/
      img.style.width = w / 2 + 'px'
      /*create slider:*/
      slider = document.createElement('DIV')
      slider.setAttribute('class', 'img-comp-slider')
      /*insert slider*/
      img.parentElement.insertBefore(slider, img)
      /*position the slider in the middle:*/
      slider.style.top = h / 2 - slider.offsetHeight / 2 + 'px'
      slider.style.left = w / 2 - slider.offsetWidth / 2 + 'px'
      /*execute a function when the mouse button is pressed:*/
      slider.addEventListener('mousedown', slideReady)
      /*and another function when the mouse button is released:*/
      window.addEventListener('mouseup', slideFinish)
      /*or touched (for touch screens:*/
      slider.addEventListener('touchstart', slideReady)
      /*and released (for touch screens:*/
      window.addEventListener('touchend', slideFinish)
      function slideReady(e) {
        /*prevent any other actions that may occur when moving over the image:*/
        e.preventDefault()
        /*the slider is now clicked and ready to move:*/
        clicked = 1
        /*execute a function when the slider is moved:*/
        window.addEventListener('mousemove', slideMove)
        window.addEventListener('touchmove', slideMove)
      }
      function slideFinish() {
        /*the slider is no longer clicked:*/
        clicked = 0
      }
      function slideMove(e) {
        var pos
        /*if the slider is no longer clicked, exit this function:*/
        if (clicked == 0) return false
        /*get the cursor's x position:*/
        pos = getCursorPos(e)
        /*prevent the slider from being positioned outside the image:*/
        if (pos < 0) pos = 0
        if (pos > w) pos = w
        /*execute a function that will resize the overlay image according to the cursor:*/
        slide(pos)
      }
      function getCursorPos(e) {
        var a,
          x = 0
        e = e.changedTouches ? e.changedTouches[0] : e
        /*get the x positions of the image:*/
        a = img.getBoundingClientRect()
        /*calculate the cursor's x coordinate, relative to the image:*/
        x = e.pageX - a.left
        /*consider any page scrolling:*/
        x = x - window.pageXOffset
        return x
      }
      function slide(x) {
        /*resize the image:*/
        img.style.width = x + 'px'
        /*position the slider:*/
        slider.style.left = img.offsetWidth - slider.offsetWidth / 2 + 'px'
      }
    }
  }
</script>
  <div class="content mb-6 p-5 ">
    <div class="row">
      <div class="col-sm-6">
        <div class="row d-flex justify-content-center" style="margin-right: auto;">
          <div class="img-comp-container">
            <div class="img-comp-img">
              <img src="{{ art.image1.url }}" width="500" height="auto" />
            </div>
            <div class="img-comp-img img-comp-overlay">
              <img src="{{ art.image2.url }}" width="500" height="auto" />
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="row">
          <h1>{{ art.title }}</h1>
          <p>{{ art.price }}$</p>
          <p>{{ art.description }}</p>
        </div>
      </div>
    </div>
  </div>

  <script>
    /*Execute a function that will execute an image compare function for each element with the img-comp-overlay class:*/
    initComparisons();
    </script>
{% endblock %}

art/templates/art/create_art.html
{% extends 'home/layout.html' %}

{% block content %}
  <div class="container mt-5" style="padding-bottom: 100vh;">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="accordion" id="accordionInput">
          <div class="accordion-item">
            <h2 class="accordion-header bg-dark" id="headingInput">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseInput" aria-expanded="flase" aria-controls="collapseInput">
                Input
              </button>
            </h2>
            <div id="collapseInput" class="accordion-collapse collapse" aria-labelledby="headingInput" data-bs-parent="#accordionInput">
              <div class="accordion-body bg-black">
                <div class="row text-white">
                  <form action="{% url 'art:create_art' %}" method="post" enctype="multipart/form-data" id="formCreateArt">
                    {% csrf_token %}
                    <div class="row bg-dark p-2">
                      <label for="image" class="form-label" id="image">Chọn hình ảnh</label>
                      <input type="file" name="image" id="image" />
                    </div>
                    <div class="row bg-dark mt-2 p-2">
                      <label for="pull_amount" class="form-label">Số lượng đường chỉ</label>
                      <input type="range" id="pull_amount" name="pull_amount" class="form-range" step="10" min="100" max="10000" value="1500" />
                      <span id="pull_amount_value">1500</span>
                      <p class="text-danger" id="pull_amount_warning" style="display: none;">Số lượng càng lớn, xử lý càng chậm!!!</p>
                    </div>
                    <div class="row bg-dark mt-2 p-2">
                      <label for="side_len" class="form-label">Độ mỏng chỉ</label>
                      <input type="range" id="side_len" name="side_len" class="form-range" step="1" min="0" max="1000" value="300" />
                      <span id="side_len_value">300</span>
                      <p class="text-danger" style="display: none;" id="side_len_warning">độ mỏng càng lớn ảnh càng rõ nét, độ cháy ảnh càng cao!!!</p>
                    </div>
                    <div class="row bg-dark mt-2 p-2">
                      <label for="export_strength" class="form-label">Độ sáng ảnh</label>
                      <input type="range" id="export_strength" name="export_strength" class="form-range" step="0.01" min="0.01" max="0.1" value="0.05" />
                      <span id="export_strength_value">0.05</span>
                      <p class="text-white" style="display: block;" id="positive_export_strength_warning">độ sáng càng lớn, ảnh càng tối!!!</p>
                    </div>
                    <div class="row bg-dark mt-2 p-2">
                      <label for="random_nails" class="form-label">Số lượng đinh xét mỗi lần duyệt</label>
                      <input type="range" id="random_nails" name="random_nails" class="form-range" step="10" min="100" max="500" value="300" />
                      <span id="random_nails_value">300</span>
                      <p class="text-white" style="display: block;" id="random_nails_warning">Càng nhiều đinh, ảnh càng đẹp, xử lý càng chậm!!!</p>
                    </div>
                    <div class="row bg-dark mt-2 p-2">
                      <label for="nail_step" class="form-label">Khoảng cách đinh neo</label>
                      <input type="range" id="nail_step" name="nail_step" class="form-range" step="1" min="1" max="10" value="4" />
                      <span id="nail_step_value">4</span>
                      <p class="text-white" style="display: block;" id="nail_step_warning">Khoảng cách càng bé, càng nhiều đinh neo, ảnh càng đẹp, xử lý càng chậm!!!</p>
                    </div>
                    <div class="row bg-dark mt-2 p-2">
                      <label for="form-check" class="form-label">Lựa chọn nền ảnh</label>
                      <div class="form-check">
                        <input type="radio" class="form-check-input" id="radio1_wb" name="wb" value="False" checked />Nền trắng
                        <label class="form-check-label" for="radio1_wb"></label>
                      </div>
                      <div class="form-check">
                        <input type="radio" class="form-check-input" id="radio2_wb" name="wb" value="True" />Nền đen
                        <label class="form-check-label" for="radio2_wb"></label>
                      </div>
                    </div>
                    <div class="row bg-dark mt-2 p-2">
                      <label for="form-check" class="form-label">Trắng đen/màu</label>
                      <div class="form-check">
                        <input type="radio" class="form-check-input" id="radio1_rgb" name="rgb" value="False" checked />Trắng đen
                        <label class="form-check-label" for="radio1_rgb"></label>
                      </div>
                      <div class="form-check">
                        <input type="radio" class="form-check-input" id="radio2_rgb" name="rgb" value="True" />Màu
                        <label class="form-check-label" for="radio2_rgb"></label>
                      </div>
                    </div>
                    <div class="row bg-dark mt-2 p-2">
                      <label for="form-check" class="form-label">Hình dạng khung</label>
                      <div class="form-check">
                        <input type="radio" class="form-check-input" id="radio1_rect" name="rect" value="True" />Hình vuông
                        <label class="form-check-label" for="radio1_rect"></label>
                      </div>
                      <div class="form-check">
                        <input type="radio" class="form-check-input" id="radio2_rect" name="rect" value="False" checked />Hình tròn
                        <label class="form-check-label" for="radio2_rect"></label>
                      </div>
                    </div>
                      <button type="submit" class="btn btn-primary mt-3 mr-auto">Bắt đầu</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>

        {% if image_result %}
        <div class="accordion mt-2" id="accordionOutput">
          <div class="accordion-item">
            <h2 class="accordion-header bg-dark" id="headingOutput">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOutput" aria-expanded="true" aria-controls="collapseOutput">
                Output
              </button>
            </h2>
            <div id="collapseOutput" class="accordion-collapse collapse" aria-labelledby="headingOutput" data-bs-parent="#accordionOutput">
              <div class="accordion-body bg-black">
                  <div class="row justify-content-center">
                    <img src="{{ image_result }}" alt="Result Image" />
                  </div>
                  <a href="{{ image_result }}" download="result_image.jpg" class="btn btn-primary mt-3 mr-auto">Tải ảnh về</a>
                </div>
            </div>
          </div>
        </div>
        {% if user.is_authenticated %}
        <div class="accordion mt-2" id="accordionSave">
          <div class="accordion-item">
            <h2 class="accordion-header bg-dark" id="headingSave">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSave" aria-expanded="true" aria-controls="collapseSave">
                Lưu ảnh
              </button>
            </h2>
            <div id="collapseSave" class="accordion-collapse collapse" aria-labelledby="headingSave" data-bs-parent="#accordionSave">
              <div class="accordion-body bg-black">
                  <div class="row justify-content-center">
                    <form action="{% url 'art:save_art' user.id %}" method="post" class="text-white" id="formSaveArt">
                      {% csrf_token %}
                      <div class="row bg-dark mt-2 p-2">
                        <label for="title" class="form-label">Tên ảnh</label>
                        <input type="text" class="form-control" id="title" name="title" />
                      </div>
                      <div class="row bg-dark mt-2 p-2">
                        <label for="description" class="form-label">Mô tả chi tiết</label>
                        <input type="text" class="form-control" id="description" name="description"/>
                      </div>
                      <div class="row bg-dark mt-2 p-2">
                        <label for="is_published" class="form-label">Bạn có muốn chia sẻ ảnh này</label>
                        <input type="radio" class="form-check-input" id="radio_is_published" name="is_published" value="True"/>Tôi muốn chia sẻ
                      </div>
                      <button type="submit" class="btn btn-primary mt-3 mr-auto">Lưu ảnh</button>
                    </form>
                  </div>
                </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endif %}
    </div>
  </div>

  <script>
    var pullAmountRange = document.getElementById('pull_amount')
    var pullAmountValue = document.getElementById('pull_amount_value')
    var pullAmountWarning = document.getElementById('pull_amount_warning')
    
    // Bắt sự kiện khi giá trị của input range thay đổi
    pullAmountRange.addEventListener('input', function () {
      // Lấy giá trị của input range
      var value = this.value
      // Hiển thị giá trị trong một phần tử HTML
      pullAmountValue.innerHTML = value
      if (value >= 5000) {
        pullAmountWarning.style.display = 'block'
      } else {
        pullAmountWarning.style.display = 'none'
      }
    })
    
    var sideLenRange = document.getElementById('side_len')
    var sideLenValue = document.getElementById('side_len_value')
    var sideLenWarning = document.getElementById('side_len_warning')
    
    // Bắt sự kiện khi giá trị của input range thay đổi
    sideLenRange.addEventListener('input', function () {
      // Lấy giá trị của input range
      var value = this.value
      // Hiển thị giá trị trong một phần tử HTML
      sideLenValue.innerHTML = value
      if (value >= 400) {
        sideLenWarning.style.display = 'block'
      } else {
        sideLenWarning.style.display = 'none'
      }
    })
    var export_strengthRange = document.getElementById('export_strength')
    var export_strengthValue = document.getElementById('export_strength_value')
    var positive_export_strength_warning = document.getElementById('positive_export_strength_warning')
    var negative_export_strength_warning = document.getElementById('negative_export_strength_warning')
    
    // Bắt sự kiện khi giá trị của input range thay đổi
    export_strengthRange.addEventListener('input', function () {
      // Lấy giá trị của input range
      var value = this.value
      // Hiển thị giá trị trong một phần tử HTML
      export_strengthValue.innerHTML = value
      if (value >= 0) {
        positive_export_strength_warning.style.display = 'block'
        negative_export_strength_warning.style.display = 'none'
      } else {
        positive_export_strength_warning.style.display = 'none'
        negative_export_strength_warning.style.display = 'block'
      }
    })
    
    var random_nailsRange = document.getElementById('random_nails')
    var random_nailsValue = document.getElementById('random_nails_value')
    var random_nailsWarning = document.getElementById('random_nails_warning')
    // Bắt sự kiện khi giá trị của input range thay đổi
    random_nailsRange.addEventListener('input', function () {
      // Lấy giá trị của input range
      var value = this.value
      // Hiển thị giá trị trong một phần tử HTML
      random_nailsValue.innerHTML = value
      if (value >= 400) {
        random_nailsWarning.style.display = 'block'
      } else {
        random_nailsWarning.style.display = 'none'
      }
    })
    
    var nail_stepRange = document.getElementById('nail_step')
    var nail_stepValue = document.getElementById('nail_step_value')
    var nail_stepWarning = document.getElementById('nail_step_warning')
    // Bắt sự kiện khi giá trị của input range thay đổi
    nail_stepRange.addEventListener('input', function () {
      // Lấy giá trị của input range
      var value = this.value
      // Hiển thị giá trị trong một phần tử HTML
      nail_stepValue.innerHTML = value
      if (value >= 4) {
        nail_stepWarning.style.display = 'block'
      } else {
        nail_stepWarning.style.display = 'none'
      }
    })

  </script>
{% endblock %}